apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: hack-2026-prod

# Reference the base
bases:
- ../../

# Prod-specific settings
commonLabels:
  environment: production
  app.kubernetes.io/version: stable

commonAnnotations:
  config.kubernetes.io/environment: production
  deployment.kubernetes.io/tier: production

# Prod patch: ensure 3 replicas of ESO for HA
patchesStrategicMerge:
- eso-replicas-patch.yaml

# Resource names
namePrefix: prod-

# Prod namespace override
namespace: production
