apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secrets
  labels:
    app.kubernetes.io/name: gcp-secrets
    app.kubernetes.io/part-of: external-secrets
spec:
  provider:
    gcpsm:
      projectID: inert-synergies-llc
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: hack-gke-primary
          serviceAccountRef:
            name: external-secrets-operator
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secrets
  namespace: default
spec:
  provider:
    gcpsm:
      projectID: inert-synergies-llc
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: hack-gke-primary
          serviceAccountRef:
            name: external-secrets-operator
            namespace: external-secrets
