apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: eso-operator@inert-synergies-llc.iam.gserviceaccount.com
