from app.models import IncidentCard, utcnow

FALLBACK_MODEL = "fallback-cache-travis-v1"


def demo_incidents() -> list[IncidentCard]:
    """Fixed Travis/Williamson demo pins. Not a substitute for a citizen report."""
    now = utcnow()
    return [
        IncidentCard(
            incident_id="INC-DEMO01",
            timestamp=now,
            category="ROAD_OBSTRUCTION",
            severity="HIGH",
            summary="Downed live oak blocking RM 620 near Round Rock.",
            target_agency="COUNTY_PUBLIC_WORKS",
            confidence_score=0.91,
            latitude=30.5084,
            longitude=-97.6789,
            model_name=FALLBACK_MODEL,
        ),
        IncidentCard(
            incident_id="INC-DEMO02",
            timestamp=now,
            category="TRAFFIC_SIGNAL",
            severity="HIGH",
            summary="Traffic signal dark at Parmer Lane and Dessau Road.",
            target_agency="311_DISPATCH",
            confidence_score=0.88,
            latitude=30.3879,
            longitude=-97.6654,
            model_name=FALLBACK_MODEL,
        ),
        IncidentCard(
            incident_id="INC-DEMO03",
            timestamp=now,
            category="WATER_FLOODING",
            severity="CRITICAL",
            summary="Submerged low-water crossing at Spicewood Springs Road.",
            target_agency="EMERGENCY_SERVICES",
            confidence_score=0.93,
            latitude=30.4186,
            longitude=-97.7668,
            model_name=FALLBACK_MODEL,
        ),
        IncidentCard(
            incident_id="INC-DEMO04",
            timestamp=now,
            category="ELECTRICAL",
            severity="CRITICAL",
            summary="Transformer flashover near Braker Lane.",
            target_agency="AUSTIN_ENERGY",
            confidence_score=0.9,
            latitude=30.3904,
            longitude=-97.7169,
            model_name=FALLBACK_MODEL,
        ),
        IncidentCard(
            incident_id="INC-DEMO05",
            timestamp=now,
            category="ROAD_OBSTRUCTION",
            severity="HIGH",
            summary="Sinkhole developing on Brushy Creek Road, Cedar Park.",
            target_agency="COUNTY_PUBLIC_WORKS",
            confidence_score=0.86,
            latitude=30.5052,
            longitude=-97.8201,
            model_name=FALLBACK_MODEL,
        ),
        IncidentCard(
            incident_id="INC-DEMO06",
            timestamp=now,
            category="ROAD_OBSTRUCTION",
            severity="MODERATE",
            summary="Pecan limbs in the westbound lane of RM 1431 at Lake Creek.",
            target_agency="COUNTY_PUBLIC_WORKS",
            confidence_score=0.81,
            latitude=30.5089,
            longitude=-97.8214,
            model_name=FALLBACK_MODEL,
        ),
        IncidentCard(
            incident_id="INC-DEMO07",
            timestamp=now,
            category="WATER_FLOODING",
            severity="HIGH",
            summary="Walnut Creek overtopping the low-water crossing on Cameron Road.",
            target_agency="311_DISPATCH",
            confidence_score=0.84,
            latitude=30.3374,
            longitude=-97.6658,
            model_name=FALLBACK_MODEL,
        ),
        IncidentCard(
            incident_id="INC-DEMO08",
            timestamp=now,
            category="TRAFFIC_SIGNAL",
            severity="MODERATE",
            summary="Flashing reds at Lamar Boulevard and 45th Street after a pole strike.",
            target_agency="311_DISPATCH",
            confidence_score=0.8,
            latitude=30.3122,
            longitude=-97.7396,
            model_name=FALLBACK_MODEL,
        ),
        IncidentCard(
            incident_id="INC-DEMO09",
            timestamp=now,
            category="ELECTRICAL",
            severity="HIGH",
            summary="Neighborhood outage after a line slap on University Boulevard, Round Rock.",
            target_agency="AUSTIN_ENERGY",
            confidence_score=0.83,
            latitude=30.5136,
            longitude=-97.6879,
            model_name=FALLBACK_MODEL,
        ),
        IncidentCard(
            incident_id="INC-DEMO10",
            timestamp=now,
            category="ROAD_OBSTRUCTION",
            severity="LOW",
            summary="Fallen oak debris on the shoulder of SH 29 east of Georgetown.",
            target_agency="COUNTY_PUBLIC_WORKS",
            confidence_score=0.76,
            latitude=30.6332,
            longitude=-97.6411,
            model_name=FALLBACK_MODEL,
        ),
    ]
