from app.models import IncidentCard

FALLBACK_MODEL = "fallback-cache-travis-v1"

SEEDED_INCIDENTS: list[IncidentCard] = [
    IncidentCard(
        incident_id="INC-1001",
        category="ELECTRICAL",
        severity="CRITICAL",
        summary="Downed live oak limbs sagging directly across transformer wires.",
        target_agency="AUSTIN_ENERGY",
        confidence_score=0.98,
        latitude=30.4398,
        longitude=-97.6200,
        address="Pecan St & Swenson Blvd, Pflugerville",
        model_name=FALLBACK_MODEL,
    ),
    IncidentCard(
        incident_id="INC-1002",
        category="WATER_FLOODING",
        severity="HIGH",
        summary="Submerged roadway dip with standing storm water near Heatherwilde.",
        target_agency="EMERGENCY_SERVICES",
        confidence_score=0.95,
        latitude=30.4485,
        longitude=-97.6650,
        address="Wells Branch Pkwy near Heatherwilde",
        model_name=FALLBACK_MODEL,
    ),
    IncidentCard(
        incident_id="INC-1003",
        category="TRAFFIC_SIGNAL",
        severity="CRITICAL",
        summary="Traffic signal dark at Parmer Ln and Dessau Rd.",
        target_agency="311_DISPATCH",
        confidence_score=0.99,
        latitude=30.4610,
        longitude=-97.5980,
        address="Parmer Ln & Dessau Rd",
        model_name=FALLBACK_MODEL,
    ),
    IncidentCard(
        incident_id="INC-1004",
        category="ROAD_OBSTRUCTION",
        severity="MODERATE",
        summary="Downed live oak blocking RM 620 near Round Rock.",
        target_agency="COUNTY_PUBLIC_WORKS",
        confidence_score=0.91,
        latitude=30.5080,
        longitude=-97.6780,
        address="RM 620, Round Rock",
        model_name=FALLBACK_MODEL,
    ),
    IncidentCard(
        incident_id="INC-1005",
        category="WATER_FLOODING",
        severity="CRITICAL",
        summary="Submerged low-water crossing at Spicewood Springs Rd.",
        target_agency="EMERGENCY_SERVICES",
        confidence_score=0.96,
        latitude=30.3900,
        longitude=-97.7600,
        address="Spicewood Springs Rd",
        model_name=FALLBACK_MODEL,
    ),
    IncidentCard(
        incident_id="INC-1006",
        category="ELECTRICAL",
        severity="CRITICAL",
        summary="Transformer flashover near Braker Ln.",
        target_agency="AUSTIN_ENERGY",
        confidence_score=0.97,
        latitude=30.3800,
        longitude=-97.6890,
        address="N Lamar Blvd & Braker Ln, Austin",
        model_name=FALLBACK_MODEL,
    ),
    IncidentCard(
        incident_id="INC-1007",
        category="ROAD_OBSTRUCTION",
        severity="HIGH",
        summary="Sinkhole developing on Brushy Creek Rd, Cedar Park.",
        target_agency="COUNTY_PUBLIC_WORKS",
        confidence_score=0.93,
        latitude=30.5050,
        longitude=-97.7320,
        address="Parmer Ln & Brushy Creek Rd, Cedar Park",
        model_name=FALLBACK_MODEL,
    ),
    IncidentCard(
        incident_id="INC-1008",
        category="OTHER",
        severity="LOW",
        summary="Damaged street sign leaning over the sidewalk in Hutto.",
        target_agency="311_DISPATCH",
        confidence_score=0.86,
        latitude=30.5420,
        longitude=-97.5510,
        address="US-79 & Chris Kelley Blvd, Hutto",
        model_name=FALLBACK_MODEL,
    ),
]
