apiVersion: v1
kind: ServiceAccount
metadata:
  name: civicpulse
  namespace: civicpulse
  labels:
    app.kubernetes.io/name: civicpulse
  annotations:
    iam.gke.io/gcp-service-account: civicpulse@inert-synergies-llc.iam.gserviceaccount.com
