apiVersion: v1
kind: Service
metadata:
  name: civicpulse
  namespace: civicpulse
  labels:
    app.kubernetes.io/name: civicpulse
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: civicpulse
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
