apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: civicpulse-staging

patches:
  - target:
      kind: Namespace
      name: civicpulse
    patch: |-
      - op: replace
        path: /metadata/name
        value: civicpulse-staging

replicas:
  - name: civicpulse
    count: 1

labels:
  - pairs:
      environment: staging
      lornu.ai/cluster: inert-synergies-llc
    includeSelectors: false
